name: CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Build Tools
      run: |
        sudo apt update
        sudo apt install -y gcc python3 rustc

    - name: Build and Run C
      working-directory: ./c
      run: |
        echo "--- Building C ---"
        gcc *.c -o app
        echo "--- Running C ---"
        ./app

    - name: Build and Run Rust
      working-directory: ./rust
      run: |
        echo "--- Building Rust ---"
        rustc helloworld.rs -o hello_rust
        echo "--- Running Rust ---"
        ./hello_rust

    - name: Run Python
      working-directory: ./python
      run: |
        echo "--- Running Python ---"
        python3 HelloWorld.py
